version: "3"

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  app:
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
#      - redis
#  redis:
#    image: redis:alpine
#    restart: always
#    container_name: redis_db
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis-data:/data
#volumes:
#  redis-data: