spring:
  application:
    name: app
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5433/db
    password: ${SPRING_DATASOURCE_PASSWORD}
    username: ${SPRING_DATASOURCE_USERNAME}
  jwt:
    secret: ${SPRING_JWT_SECRET}
    expiration: 3600000
#  redis:
#    host: localhost
#    port: 6379