import type { Metadata } from "next";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import LayoutAuth from "@/components/common/LayoutAuth";

import { Roboto } from "next/font/google"

const robotoFont = Roboto({
  subsets: ["latin"],
  weight: "400"
})

export const metadata: Metadata = {
  title: "ToDo Task",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoFont.className}`}
        >
          <SessionProvider>
            <LayoutAuth>
                {children}
            </LayoutAuth>
          </SessionProvider>
      </body>
    </html>
  );
}
